Repository redhat-cop/containers-quickstarts, pull requests merged in 2019-09, with the labels that each got.

#243 Add scl_enable to jenkins-slave-ansible to enable python 3.6
  .applier/group_vars/seed-hosts.yml
  jenkins-slaves/jenkins-slave-ansible/Dockerfile
  jenkins-slaves/jenkins-slave-ansible/Jenkinsfile.test
Labels: bug

#250 Fix sonarqube builds and use latest release
  sonarqube/.applier/group_vars/seed-hosts.yml
  sonarqube/.openshift/templates/sonarqube-deployment-template.yml
  sonarqube/README.md
  sonarqube/sonar.properties
Labels: bug, enhancement

#113 Added gradle s2i builder images
  s2i-mvn-gradle/Dockerfile
  s2i-mvn-gradle/Makefile
  s2i-mvn-gradle/README.md
  s2i-mvn-gradle/s2i/bin/assemble
  s2i-mvn-gradle/s2i/bin/functions
  s2i-mvn-gradle/s2i/bin/run
  s2i-mvn-gradle/s2i/bin/save-artifacts
  s2i-mvn-gradle/s2i/bin/usage
  s2i-mvn-gradle/test/run
  s2i-mvn-gradle/test/test-app-gradle/build.gradle
  s2i-mvn-gradle/test/test-app-gradle/src/build.gradle
  s2i-mvn-gradle/test/test-app-gradle/src/main/java/net/woodmen/S2iApplication.java
  s2i-mvn-gradle/test/test-app-gradle/src/test/java/net/woodmen/S2iApplicationTests.java
  s2i-mvn-gradle/test/test-app-maven/pom.xml
  s2i-mvn-gradle/test/test-app-maven/src/main/java/hello/Application.java
  s2i-mvn-gradle/test/test-app/index.html
Labels: enhancement

#216 Update cluster-lifecycle -> openshift-templates
  build-docker-generic/.applier/group_vars/seed-hosts.yml
  build-s2i-executable/.applier/group_vars/seed-hosts.yml
  build-s2i-gows/.applier/group_vars/seed-hosts.yml
  build-s2i-jekyll/.applier/group_vars/seed-hosts.yml
  build-s2i-liberty/.applier/group_vars/seed-hosts.yml
  build-s2i-play/.applier/group_vars/seed-hosts.yml
  gitlab-ce/.applier/group_vars/seed-hosts.yml
  gogs/.applier/group_vars/seed-hosts.yml
  hoverfly/.applier/group_vars/seed-hosts.yml
  mongodb/.applier/group_vars/seed-hosts.yml
  rabbitmq/.applier/group_vars/seed-hosts.yml
  sonarqube/.applier/group_vars/seed-hosts.yml
  tool-box/.applier/group_vars/seed-hosts.yml
Labels: enhancement

#221 Update ruby slave to ruby 2.5
  .openshift/params/ruby
  .openshift/params/test_pipelines/ruby
  .openshift/templates/jenkins-slave-generic-template.yml
  _test/setup.sh
  jenkins-slaves/jenkins-slave-ruby/Dockerfile
  jenkins-slaves/jenkins-slave-ruby/Dockerfile.rhel7
  jenkins-slaves/jenkins-slave-ruby/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-ruby/root/opt/app-root/etc/scl_enable
Labels: enhancement

#255 Fix small typo for consistency
  CONTRIBUTING.md
  README.md
Labels: enhancement

#256 Fixing MongoDB Project Template URL in seed-hosts.yml
  mongodb/.applier/group_vars/seed-hosts.yml
Labels: bug

#254 Creating UBI8 base tool-box image
  tool-box/Dockerfile
  tool-box/README.md
Labels: enhancement

#217 Add ipa
  .gitignore
  ipa-server/.applier/group_vars/seed-hosts.yml
  ipa-server/.applier/hosts
  ipa-server/README.md
  ipa-server/requirements.yml
Labels: enhancement

#252 Use UBI for jenkins-slave-ruby and add to testing
  .applier/group_vars/seed-hosts.yml
  .openshift/params/ruby
  .openshift/params/test_pipelines/ruby
  jenkins-slaves/jenkins-slave-ruby/Dockerfile
  jenkins-slaves/jenkins-slave-ruby/Dockerfile.rhel7
  jenkins-slaves/jenkins-slave-ruby/README.md
  jenkins-slaves/jenkins-slave-ruby/root/opt/app-root/etc/scl_enable
  jenkins-slaves/jenkins-slave-ruby/ubi.repo
Labels: enhancement
