Repository redhat-cop/containers-quickstarts, pull requests merged in 2019-11, with the labels that each got.

#269 Update Rabbitmq to 3.8.0, fixes #265
  _test/common.sh
  _test/rabbitmq.sh
  rabbitmq/.applier/group_vars/seed-hosts.yml
  rabbitmq/.openshift/templates/builds/template.yml
  rabbitmq/.openshift/templates/configmaps/config.yml
  rabbitmq/.openshift/templates/deployments/template.yml
  rabbitmq/Dockerfile
  rabbitmq/README.md
  rabbitmq/docker-entrypoint.sh
  rabbitmq/requirements.yml
Labels: approved, size/XL

#272 Add quickstart to deploy OCP4 cluster-logging
  ocp4-logging/.applier/group_vars/seed-hosts.yml
  ocp4-logging/.applier/host_vars/localhost.yml
  ocp4-logging/.applier/hosts
  ocp4-logging/.openshift/params/cl-catalogsourceconfig.params
  ocp4-logging/.openshift/params/cl-resource.params
  ocp4-logging/.openshift/params/cl-subscription.params
  ocp4-logging/.openshift/params/cluster-logging.params
  ocp4-logging/.openshift/params/es-catalogsourceconfig.params
  ocp4-logging/.openshift/params/es-subscription.params
  ocp4-logging/.openshift/params/operatorgroup.params
  ocp4-logging/.openshift/templates/README.md
  ocp4-logging/.openshift/templates/ocp4-logging-cr.yml
  ocp4-logging/README.md
  ocp4-logging/galaxy-requirements.yml
  ocp4-logging/requirements.yml
Labels: approved, lgtm, size/L

#273 Update ipa quickstart for OCP4
  ipa-server/.applier/group_vars/seed-hosts.yml
  ipa-server/.openshift/files/01-worker-sebool.yml
  ipa-server/README.md
  ipa-server/requirements.yml
Labels: approved, lgtm, size/M
