Repository redhat-cop/containers-quickstarts, pull requests merged in 2019-10, with the labels that each got.

#264 Add OWNERS file
  OWNERS
Labels: size/S

#266 Fix jenkins-slave-mvn to actually have mvn
  .applier/group_vars/seed-hosts.yml
  jenkins-slaves/jenkins-slave-mvn/Dockerfile
  jenkins-slaves/jenkins-slave-mvn/Jenkinsfile.test
Labels: approved, enhancement, lgtm, size/M

#263 Update RabbitMQ to use UBI
  rabbitmq/.openshift/templates/builds/template.yml
  rabbitmq/.openshift/templates/imagestreams/images.yml
  rabbitmq/Dockerfile
  rabbitmq/README.md
Labels: approved, enhancement, lgtm, size/S

#267 Updates to s2i play
  build-s2i-play/.openshift/templates/build.yml
  build-s2i-play/README.md
Labels: approved, lgtm, size/M

#268 Fix dead links
  build-s2i-executable/README.md
  build-s2i-gows/README.md
  build-s2i-jekyll/README.md
  build-s2i-liberty/README.md
  build-s2i-play/README.md
  mongodb/README.md
  rabbitmq/README.md
Labels: approved, lgtm, size/S

#270 Use Prow build badge
  README.md
Labels: approved, lgtm, size/XS
