Repository redhat-cop/containers-quickstarts, pull requests merged in 2019-12, with the labels that each got.

#258 sonarqube: use openshift oauth for login
  sonarqube/.applier/group_vars/seed-hosts.yml
  sonarqube/.openshift/templates/sonarqube-deployment-template.yml
  sonarqube/Dockerfile
  sonarqube/README.md
  sonarqube/sonar.properties
Labels: lgtm

#277 Added methods to download jenkins log for builds
  _test/common.sh
  _test/setup.sh
Labels: approved, lgtm, size/M

#278 Updated jenkins slaves to 4.2 bases
  .applier/group_vars/seed-hosts.yml
  .openshift/templates/jenkins-slave-generic-template.j2
  jenkins-slaves/jenkins-slave-ansible/Dockerfile
  jenkins-slaves/jenkins-slave-arachni/Dockerfile
  jenkins-slaves/jenkins-slave-golang/Dockerfile
  jenkins-slaves/jenkins-slave-gradle/Dockerfile
  jenkins-slaves/jenkins-slave-mongodb/Dockerfile
  jenkins-slaves/jenkins-slave-mvn/Dockerfile
  jenkins-slaves/jenkins-slave-python/Dockerfile
  jenkins-slaves/jenkins-slave-ruby/Dockerfile
Labels: approved, lgtm, size/S
