Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-06, with the labels that each got.

#352 upload-file-to-google-drive.py - init add
  .github/workflows/ubi8-google-api-python-client-pr.yaml
  utilities/ubi8-google-api-python-client/Dockerfile
  utilities/ubi8-google-api-python-client/README.md
  utilities/ubi8-google-api-python-client/root/usr/local/bin/upload-file-to-google-drive
  utilities/ubi8-google-api-python-client/version.json
Labels: approved, lgtm, ok-to-test, size/L

#354 Added github workflow action for conftest
  .github/workflows/conftest.yaml
  _test/_helpers.bash
  _test/conftest.sh
Labels: approved, lgtm, size/L

#356 Removed skip for helm related conftests
  _test/conftest.sh
Labels: approved, lgtm, size/XS

#358 Update Jenkins Image Mgmt to use UBI & latest skopeo
  .applier/group_vars/seed-hosts.yml
  .openshift/templates/jenkins-slave-image-mgmt-template.yml
  _test/setup.sh
  jenkins-slaves/jenkins-slave-image-mgmt/Dockerfile
  jenkins-slaves/jenkins-slave-image-mgmt/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-image-mgmt/README.md
Labels: approved, lgtm, size/L

#360 🦄 FIX - typo 🔥
  jenkins-masters/hygieia-plugin/.openshift/projects/projects.yml
Labels: approved, lgtm, size/XS

#361 🦄 Tidy up docs for Zalenium 🔥
  zalenium/README.md
Labels: approved, lgtm, size/XS

#363 🏏 Output of failed tests swallowed. Fixing 🦇
  _test/_helpers.bash
  _test/conftest.sh
Labels: approved, lgtm, size/M

#362 🦄 Tidy up docs for Toolbox and fix broken build 🔥
  tool-box/Dockerfile
  tool-box/README.md
Labels: approved, lgtm, size/M

#357 🎣 Cheeky bump to the node version, removal of chrome and base ubi 🤹‍♀️
  jenkins-slaves/jenkins-slave-npm/Dockerfile
  jenkins-slaves/jenkins-slave-npm/Dockerfile.rhel7
  jenkins-slaves/jenkins-slave-npm/README.md
  jenkins-slaves/jenkins-slave-npm/src/google-chrome.repo
Labels: approved, lgtm, size/M

#367 🦩bump argocd client 🦩
  jenkins-slaves/jenkins-slave-argocd/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#364 🦄 EMEA approvers (and Tyler) 🔥
  OWNERS
Labels: approved, lgtm, size/XS

#368 🛎 Fix api version for ocp4 happiness 🎣
  .openshift/templates/jenkins-pipeline-template-no-ocp-triggers.j2
Labels: approved, lgtm, size/XS

#370 🕵️‍♂️ Fix spelling mistake 👀
  gitlab-ce/README.md
Labels: approved, lgtm, size/XS

#371 🕵️‍♂️ Typo in the README 👀
  README.md
Labels: approved, lgtm, size/XS

#369 🛎 Bump some versions 🎣
  hoverfly/.applier/group_vars/seed-hosts.yml
  hoverfly/Dockerfile
  hoverfly/README.md
  hoverfly/requirements.yml
Labels: approved, lgtm, size/S

#373 Fix kopf peering config and bump version
  build-s2i-python-kopf/README.adoc
  build-s2i-python-kopf/install/requirements.txt
  build-s2i-python-kopf/peering-crds.yaml
  build-s2i-python-kopf/s2i/run
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/M

#372 🤯 Version fix for the slave ci 🤥
  .applier/group_vars/seed-hosts.yml
Labels: approved, lgtm, size/XS

#375 Set KOPF_NAMESPACE when KOPF_NAMESPACED is set
  build-s2i-python-kopf/s2i/run
Labels: approved, lgtm, size/XS

#374 🏏 Conftest and Bats agent for Jenkins 🦇
  .applier/group_vars/seed-hosts.yml
  jenkins-slaves/jenkins-slave-conftest/Dockerfile
  jenkins-slaves/jenkins-slave-conftest/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-conftest/README.md
Labels: approved, lgtm, size/M

#366 🦄 FIX - Helm perms 🔥
  tool-box/Dockerfile
Labels: approved, lgtm, size/XS

#376 🦩bump version to latest argocd-1.6.0🦩
  jenkins-slaves/jenkins-slave-argocd/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#379 Fix typos and update example in README
  ubi7-gitlab-runner/README.md
Labels: approved, lgtm, ok-to-test, size/S

#381 Update ruby jenkins agent to ruby 2.6
  jenkins-slaves/jenkins-slave-ruby/Dockerfile
  jenkins-slaves/jenkins-slave-ruby/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#382 Update ruby jenkins agent oc client to 4.4
  jenkins-slaves/jenkins-slave-ruby/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#384 👓 Fix readme formatting 👓
  jenkins-slaves/jenkins-slave-ruby/README.md
Labels: approved, lgtm, size/XS

#385 Update ruby jenkins agent to nodejs 12
  jenkins-slaves/jenkins-slave-ruby/Dockerfile
  jenkins-slaves/jenkins-slave-ruby/README.md
  jenkins-slaves/jenkins-slave-ruby/root/opt/app-root/etc/scl_enable
Labels: approved, lgtm, ok-to-test, size/S

#386 Bump build-s2i-python-kopf to v0.28.4 for security advisory
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/XS

#383 Fix missing selectors in StatefulSets
  mongodb/.openshift/templates/configsvr.yml
  mongodb/.openshift/templates/replset.yml
Labels: approved, lgtm, ok-to-test, size/XS
