Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-01, with the labels that each got.

#281 Remove rabbit build check
  _test/rabbitmq.sh
Labels: approved, lgtm, size/XS

#287 Enhance Jinja template to be more backward compatible and use better defaults
  .openshift/templates/jenkins-slave-generic-template.j2
Labels: approved, lgtm, size/XS

#289 Added stalebot config
  .github/stale.yml
Labels: approved, lgtm, size/M

#288 Fixes running the RabbitMQ build under a firewall
  rabbitmq/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#290 Add Gareth as reviewer of this repo
  OWNERS
Labels: approved, lgtm, size/XS

#117 Add Erlang Jenkins slave, fixes #101
  .applier/group_vars/seed-hosts.yml
  jenkins-slaves/jenkins-slave-ansible/README.md
  jenkins-slaves/jenkins-slave-erlang/Dockerfile
  jenkins-slaves/jenkins-slave-erlang/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-erlang/README.md
Labels: approved, enhancement, lgtm, size/M

#293 Updated to oc 4.3 client
  tool-box/Dockerfile
Labels: approved, lgtm, size/XS
