Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-09, with the labels that each got.

#402 🐪 updated to 1.7.2 argocd 🐪
  jenkins-agents/jenkins-agent-argocd/Dockerfile
Labels: approved, lgtm, size/XS

#403 Cert Management: Adding OCP v4 templates for use with OpenShift Applier
  cert-manager-configs/.applier/group_vars/seed-hosts.yml
  cert-manager-configs/.applier/host_vars/localhost.yml
  cert-manager-configs/.applier/hosts
  cert-manager-configs/.openshift/cert-manager.yml
  cert-manager-configs/.openshift/cert-utils-operator.yml
  cert-manager-configs/.openshift/ocpv4-certs.yml
  cert-manager-configs/README.md
Labels: approved, lgtm, size/L

#404 Publish jenkins-agent-image-mgmt to Quay.io and update to skopeo v1.1.1
  .applier/group_vars/seed-hosts.yml
  .github/workflows/jenkins-agent-image-mgmt-pr.yaml
  .github/workflows/jenkins-agent-image-mgmt-publish.yaml
  jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
  jenkins-agents/jenkins-agent-image-mgmt/version.json
Labels: approved, lgtm, size/M

#405 Add GraalVM Jenkins Agent
  .applier/group_vars/seed-hosts.yml
  README.md
  jenkins-agents/jenkins-agent-graalvm/Dockerfile
  jenkins-agents/jenkins-agent-graalvm/Jenkinsfile.test
  jenkins-agents/jenkins-agent-graalvm/README.md
  jenkins-agents/jenkins-agent-graalvm/settings.xml
  jenkins-agents/jenkins-agent-graalvm/ubi.repo
Labels: approved, lgtm, size/L

#406 tool-box: Fixing README bug + updating versions
  tool-box/Dockerfile
  tool-box/README.md
Labels: approved, lgtm, size/S

#409 Update asciidoctor image to latest released versions
  utilities/ubi8-asciidoctor/Dockerfile
  utilities/ubi8-asciidoctor/version.json
Labels: approved, lgtm, ok-to-test, size/S

#410 Make utilities/ubi8-asciidoctor image significantly smaller
  utilities/ubi8-asciidoctor/Dockerfile
  utilities/ubi8-asciidoctor/version.json
Labels: approved, lgtm, ok-to-test, size/M
