Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-05, with the labels that each got.

#331 re-organize images that wern't GitLab runner specific to utilities/ and add more workflows
  .github/workflows/ubi7-gitlab-runner-pr.yaml
  .github/workflows/ubi7-gitlab-runner-publish.yaml
  .github/workflows/ubi8-asciidoctor-pr.yaml
  .github/workflows/ubi8-asciidoctor-publish.yaml
  .github/workflows/ubi8-git-pr.yaml
  .github/workflows/ubi8-git-publish.yaml
  .github/workflows/ubi8-google-api-python-client-pr.yaml
  .github/workflows/ubi8-google-api-python-client-publish.yaml
  gitlab-runners/README.md
  gitlab-runners/ubi8-asciidoctor/README.md
  gitlab-runners/ubi8-git/README.md
  gitlab-runners/ubi8-google-api-python-client/README.md
  ubi7-gitlab-runner/.openshift/bc-ubi7-gitlab-runner.yml
  ubi7-gitlab-runner/Dockerfile
  ubi7-gitlab-runner/README.md
  ubi7-gitlab-runner/entrypoint
  ubi7-gitlab-runner/version.json
  utilities/README.md
  utilities/ubi8-asciidoctor/.openshift/bc-ubi8-asciidoctor.yml
  utilities/ubi8-asciidoctor/Dockerfile
  utilities/ubi8-asciidoctor/README.md
  utilities/ubi8-asciidoctor/version.json
  utilities/ubi8-git/.openshift/bc-ubi8-git.yml
  utilities/ubi8-git/Dockerfile
  utilities/ubi8-git/README.md
  utilities/ubi8-git/version.json
  utilities/ubi8-google-api-python-client/.openshift/bc-ubi8-google-api-python-client.yml
  utilities/ubi8-google-api-python-client/Dockerfile
  utilities/ubi8-google-api-python-client/README.md
  utilities/ubi8-google-api-python-client/version.json
Labels: approved, lgtm, ok-to-test, size/L

#332 Move EAP to top level repo & Remove helm-charts directory
  eap/README.md
  eap/chart/Chart.yaml
  eap/chart/README.md
  eap/chart/templates/NOTES.txt
  eap/chart/templates/buildconfig.yaml
  eap/chart/templates/deploymentconfig.yaml
  eap/chart/templates/imagestream.yaml
  eap/chart/templates/ping-service.yaml
  eap/chart/templates/route.yaml
  eap/chart/templates/secret.yaml
  eap/chart/templates/server-service.yaml
  eap/chart/templates/tests/pod.yaml
  eap/chart/values.yaml
Labels: approved, lgtm, size/XS

#333 update argocd client 1.5.4
  jenkins-slaves/jenkins-slave-argocd/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#335 .github/workflows/*-publish.yaml - update to publish on git tag and tag the image with "git-TAG_NAME"
  .github/workflows/ubi7-gitlab-runner-publish.yaml
  .github/workflows/ubi8-asciidoctor-publish.yaml
  .github/workflows/ubi8-git-publish.yaml
  .github/workflows/ubi8-google-api-python-client-publish.yaml
Labels: approved, lgtm, ok-to-test, size/M

#336 🐛Bump Helm Version in the jenkins slave 🐛
  jenkins-slaves/jenkins-slave-helm/Dockerfile
Labels: approved, lgtm, size/XS

#337 utilities/ubi8-asciidoctor - add pandoc
  .github/workflows/ubi8-asciidoctor-pr.yaml
  utilities/ubi8-asciidoctor/Dockerfile
  utilities/ubi8-asciidoctor/version.json
Labels: approved, lgtm, ok-to-test, size/S

#334 Add initial Nexus helm chart
  nexus/README.md
  nexus/chart/nexus/.gitignore
  nexus/chart/nexus/.helmignore
  nexus/chart/nexus/Chart.yaml
  nexus/chart/nexus/README.md
  nexus/chart/nexus/templates/NOTES.txt
  nexus/chart/nexus/templates/_helpers.tpl
  nexus/chart/nexus/templates/rolebinding.yaml
  nexus/chart/nexus/values.yaml
Labels: approved, lgtm, size/L

#299 Add Rust jenkins agent
  .applier/group_vars/seed-hosts.yml
  jenkins-slaves/jenkins-slave-rust/Dockerfile
  jenkins-slaves/jenkins-slave-rust/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-rust/README.md
  jenkins-slaves/jenkins-slave-rust/ubi.repo
Labels: approved, lgtm, size/L

#339 Rabbitmq quay images
  .github/workflows/rabbitmq-pr.yaml
  .github/workflows/rabbitmq-publish.yaml
  rabbitmq/version.json
Labels: approved, lgtm, size/M

#341 Update RabbitMQ to 3.8.3
  rabbitmq/Dockerfile
  rabbitmq/version.json
Labels: approved, lgtm, size/XS

#343 🐛 ADD - YQ for yaml manip prior to helming stuff 🐛
  jenkins-slaves/jenkins-slave-helm/Dockerfile
Labels: approved, lgtm, size/XS

#342 Add Helm chart for RabbitMQ
  rabbitmq/README.md
  rabbitmq/chart/.helmignore
  rabbitmq/chart/Chart.yaml
  rabbitmq/chart/templates/NOTES.txt
  rabbitmq/chart/templates/_helpers.tpl
  rabbitmq/chart/templates/configmap.yaml
  rabbitmq/chart/templates/deployment.yaml
  rabbitmq/chart/templates/ingress.yaml
  rabbitmq/chart/templates/rolebinding.yaml
  rabbitmq/chart/templates/service.yaml
  rabbitmq/chart/templates/serviceaccount.yaml
  rabbitmq/chart/templates/tests/test-connection.yaml
  rabbitmq/chart/values.yaml
Labels: approved, lgtm, size/XL

#345 Feature/jenkins slave python build
  .github/workflows/jenkins-agent-python-pr.yaml
  .github/workflows/jenkins-agent-python-publish.yaml
  jenkins-slaves/jenkins-slave-python/Dockerfile
  jenkins-slaves/jenkins-slave-python/version.json
Labels: approved, lgtm, ok-to-test, size/M

#344 Updated apiVersions to fully qualified 4.x compatible
  .openshift/templates/jenkins-slave-ansible-stacks-template.yml
  .openshift/templates/jenkins-slave-generic-template.j2
  .openshift/templates/jenkins-slave-generic-template.yml
  .openshift/templates/jenkins-slave-image-mgmt-template.yml
  .openshift/templates/jenkins-slave-ruby-template.yml
  build-docker-generic/.openshift/templates/docker-build-template-binary-to-dockerimage-with-push-secret.yml
  build-docker-generic/.openshift/templates/docker-build-template-override-FROM.yml
  build-docker-generic/.openshift/templates/docker-build-template-with-secret.yml
  build-docker-generic/.openshift/templates/docker-build-template.yml
  build-s2i-executable/.openshift/templates/build-s2i-executable.yml
  build-s2i-gows/.openshift/templates/builds/template.yml
  build-s2i-gows/.openshift/templates/deployments/template.yml
  build-s2i-gows/.openshift/templates/imagestreams/template.yml
  build-s2i-jekyll/.openshift/templates/builds/docker-template.yml
  build-s2i-jekyll/.openshift/templates/builds/source-template.yml
  build-s2i-jekyll/.openshift/templates/deployments/template.yml
  build-s2i-jekyll/.openshift/templates/imagestreams/template.yml
  build-s2i-liberty/.openshift/templates/build.yml
  build-s2i-liberty/.openshift/templates/deployment.yml
  build-s2i-play/.openshift/templates/build.yml
  build-s2i-play/.openshift/templates/deployment.yml
  gitlab-ce/.openshift/templates/gitlab-ssl.yml
  gogs/.openshift/templates/gogs-persistent-template.yaml
  hoverfly/.openshift/templates/hoverfly-deployment-template.yml
  hygieia/.openshift/policy/rbac.yml
  hygieia/.openshift/templates/build-base-image.yml
  hygieia/.openshift/templates/build-exec-ui.yml
  hygieia/.openshift/templates/build-hygieia-jenkins-collector.yml
  hygieia/.openshift/templates/build-java-component.yml
  hygieia/.openshift/templates/build-ui.yml
  hygieia/.openshift/templates/deployment-exec-collector.yml
  hygieia/.openshift/templates/deployment-java-component.yml
  hygieia/.openshift/templates/deployment-ui.yml
  hygieia/.openshift/templates/docker-build-git.yml
  hygieia/.openshift/templates/hygieia-github-collector-deployment.yml
  hygieia/.openshift/templates/hygieia-jenkins-build-collector-deployment.yml
  hygieia/.openshift/templates/projects.yml
  hygieia/.openshift/templates/remote-jenkins-auth-secret.yml
  jenkins-masters/hygieia-plugin/.openshift/projects/projects.yml
  jenkins-masters/hygieia-plugin/.openshift/templates/hygieia-plugin.yml
  jenkins-masters/hygieia-plugin/.openshift/templates/jenkins-ephemeral.yml
  jenkins-masters/hygieia-plugin/.openshift/templates/jenkins-s2i.yml
  mongodb/.openshift/templates/configsvr.yml
  mongodb/.openshift/templates/mongos.yml
  mongodb/.openshift/templates/replset.yml
  ocp4-logging/.openshift/templates/ocp4-logging-cr.yml
  rabbitmq/.openshift/templates/builds/template.yml
  rabbitmq/.openshift/templates/deployments/template.yml
  rabbitmq/.openshift/templates/imagestreams/images.yml
  sonarqube/.openshift/templates/sonarqube-deployment-template.yml
  ubi7-gitlab-runner/.openshift/bc-ubi7-gitlab-runner.yml
  utilities/ubi8-asciidoctor/.openshift/bc-ubi8-asciidoctor.yml
  utilities/ubi8-git/.openshift/bc-ubi8-git.yml
  utilities/ubi8-google-api-python-client/.openshift/bc-ubi8-google-api-python-client.yml
  zalenium/.openshift/templates/projects.yml
  zalenium/.openshift/templates/zalenium-deployment.yml
Labels: approved, lgtm, size/L

#347 Fix broken links in Markdown documents
  README.md
  ubi7-gitlab-runner/README.md
  utilities/README.md
  utilities/ubi8-asciidoctor/README.md
  utilities/ubi8-git/README.md
  utilities/ubi8-google-api-python-client/README.md
Labels: approved, lgtm, size/S

#348 Fix broken s2i-liberty links
  build-s2i-liberty/README.md
Labels: approved, lgtm, size/XS

#340 Add build-python-kopf-s2i
  .github/workflows/build-s2i-python-kopf-pr.yaml
  .github/workflows/build-s2i-python-kopf-publish.yaml
  .gitignore
  README.md
  build-s2i-python-kopf/Dockerfile
  build-s2i-python-kopf/README.adoc
  build-s2i-python-kopf/build-template.yaml
  build-s2i-python-kopf/example/.s2i/bin/assemble
  build-s2i-python-kopf/example/Dockerfile
  build-s2i-python-kopf/example/README.adoc
  build-s2i-python-kopf/example/build-template.yaml
  build-s2i-python-kopf/example/deploy-template.yaml
  build-s2i-python-kopf/example/kopf-opt.sh
  build-s2i-python-kopf/example/operator/operator.py
  build-s2i-python-kopf/example/requirements.txt
  build-s2i-python-kopf/example/template.yaml
  build-s2i-python-kopf/example/test.configmap.yaml
  build-s2i-python-kopf/example/version.json
  build-s2i-python-kopf/imagestream.yaml
  build-s2i-python-kopf/install/python3-install.sh
  build-s2i-python-kopf/install/requirements.txt
  build-s2i-python-kopf/s2i/assemble
  build-s2i-python-kopf/s2i/run
  build-s2i-python-kopf/s2i/save-artifacts
  build-s2i-python-kopf/template.yaml
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/XXL

#349 Add Bats ubi8 utility image
  .github/workflows/ubi8-bats-pr.yaml
  .github/workflows/ubi8-bats-publish.yaml
  README.md
  utilities/ubi8-bats/Dockerfile
  utilities/ubi8-bats/README.md
  utilities/ubi8-bats/buildah.sh
  utilities/ubi8-bats/test/unit.bats
  utilities/ubi8-bats/version.json
Labels: approved, lgtm, size/L

#350 Add install of oc, kubectl, helm to python-kopf-s2i
  build-s2i-python-kopf/Dockerfile
  build-s2i-python-kopf/install/python3-install.sh
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/S

#346 Add Bats testing for RabbitMQ Helm chart
  rabbitmq/README.md
  rabbitmq/chart/templates/configmap.yaml
  rabbitmq/chart/values.yaml
  rabbitmq/test/acceptance/_helpers.bash
  rabbitmq/test/acceptance/rabbitmq.bats
  rabbitmq/test/unit/_helpers.bash
  rabbitmq/test/unit/configmap.bats
  rabbitmq/test/unit/rolebinding.bats
  rabbitmq/test/unit/service.bats
  rabbitmq/test/unit/serviceaccount.bats
  rabbitmq/test/unit/statefulset.bats
Labels: approved, enhancement, lgtm, size/XL

#351 Python Kopf S2I examples and docs
  .github/workflows/build-s2i-python-kopf-pr.yaml
  .gitignore
  build-s2i-python-kopf/Dockerfile
  build-s2i-python-kopf/README.adoc
  build-s2i-python-kopf/build/build_config.yaml
  build-s2i-python-kopf/build/image_stream.yaml
  build-s2i-python-kopf/build/kustomization.yaml
  build-s2i-python-kopf/example/deploy-template.yaml
  build-s2i-python-kopf/example/version.json
  build-s2i-python-kopf/examples/openshift-template-deployer/.s2i/bin/assemble
  build-s2i-python-kopf/examples/openshift-template-deployer/Dockerfile
  build-s2i-python-kopf/examples/openshift-template-deployer/README.adoc
  build-s2i-python-kopf/examples/openshift-template-deployer/build-template.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/build/build_config.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/build/custom/build_config.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/build/custom/kustomization.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/build/image_stream.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/build/kustomization.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/deploy-template.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/deploy/deployment.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/deploy/kustomization.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/kopf-opt.sh
  build-s2i-python-kopf/examples/openshift-template-deployer/operator/operator.py
  build-s2i-python-kopf/examples/openshift-template-deployer/rbac/kustomization.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/rbac/role_binding.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/rbac/service_account.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/requirements.txt
  build-s2i-python-kopf/examples/openshift-template-deployer/template.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/test/httpd-example.yaml
  build-s2i-python-kopf/examples/simple/Dockerfile
  build-s2i-python-kopf/examples/simple/README.adoc
  build-s2i-python-kopf/examples/simple/build-template.yaml
  build-s2i-python-kopf/examples/simple/build/build_config.yaml
  build-s2i-python-kopf/examples/simple/build/custom/build_config.yaml
  build-s2i-python-kopf/examples/simple/build/custom/kustomization.yaml
  build-s2i-python-kopf/examples/simple/build/image_stream.yaml
  build-s2i-python-kopf/examples/simple/build/kustomization.yaml
  build-s2i-python-kopf/examples/simple/deploy-template.yaml
  build-s2i-python-kopf/examples/simple/deploy/deployment.yaml
  build-s2i-python-kopf/examples/simple/deploy/kustomization.yaml
  build-s2i-python-kopf/examples/simple/kopf-opt.sh
  build-s2i-python-kopf/examples/simple/operator/operator.py
  build-s2i-python-kopf/examples/simple/rbac/kustomization.yaml
  build-s2i-python-kopf/examples/simple/rbac/role.yaml
  build-s2i-python-kopf/examples/simple/rbac/role_binding.yaml
  build-s2i-python-kopf/examples/simple/rbac/service_account.yaml
  build-s2i-python-kopf/examples/simple/requirements.txt
  build-s2i-python-kopf/examples/simple/test/configmap.yaml
  build-s2i-python-kopf/s2i/usage
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/XXL

#355 Removed duplicate keys
  gogs/.openshift/templates/gogs-persistent-template.yaml
  hoverfly/.openshift/templates/hoverfly-deployment-template.yml
Labels: approved, lgtm, size/XS

#353 Updated apiVersions to fully qualified 4.x compatible for SecurityContextConstraints
  gitlab-ce/.openshift/templates/gitlab-ssl.yml
  gogs/.openshift/templates/gogs-persistent-template.yaml
  mongodb/.openshift/templates/configsvr.yml
  mongodb/.openshift/templates/replset.yml
  rabbitmq/.openshift/templates/deployments/template.yml
Labels: approved, lgtm, size/S
