Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-11, with the labels that each got.

#419 Update Dockerfile
  sonarqube/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#401 Jenkins agent for python 3.8
  .gitignore
  jenkins-agents/jenkins-agent-python/Dockerfile
  jenkins-agents/jenkins-agent-python/scl_enable
Labels: approved, lgtm, ok-to-test, size/S

#420 fix images to java:8 and nodejs:10 for hygieia
  hygieia/.openshift/templates/build-base-image.yml
  hygieia/.openshift/templates/build-exec-ui.yml
  hygieia/.openshift/templates/build-hygieia-jenkins-collector.yml
  hygieia/.openshift/templates/build-java-component.yml
  hygieia/.openshift/templates/build-ui.yml
Labels: approved, lgtm, size/S

#422 🐠 updated to latest supported GA versions 🐠
  jenkins-agents/jenkins-agent-argocd/Dockerfile
Labels: approved, lgtm, size/XS
