Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-08, with the labels that each got.

#397 add molecule to jenkins-slave-ansible Dockerfile
  jenkins-agents/jenkins-agent-ansible/Dockerfile
  jenkins-agents/jenkins-agent-ansible/Jenkinsfile.test
Labels: approved, lgtm, size/XS

#399 GitHub Runner based on UBI8
  .github/workflows/github-runner-ubi8.yaml
  github-runner-ubi8/.openshift/templates/github-runner-ubi8-build.yaml
  github-runner-ubi8/.openshift/templates/github-runner-ubi8-deployment.yaml
  github-runner-ubi8/Dockerfile
  github-runner-ubi8/README.md
  github-runner-ubi8/entrypoint.sh
  github-runner-ubi8/version.json
Labels: approved, lgtm, size/L

#400 Fix Build for GitHub runner
  .github/workflows/github-runner-ubi8.yaml
  github-runner-ubi8/README.md
Labels: approved, lgtm, size/S

#394 Added bats-lib methods from central repo
  .gitignore
  _test/_helpers.bash
  _test/bats-support-clone.bash
  _test/conftest.sh
Labels: approved, lgtm, size/L
