Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-02, with the labels that each got.

#292 🍄 added argocd jenkins-slave 🍄
  .applier/group_vars/seed-hosts.yml
  jenkins-slaves/jenkins-slave-argocd/Dockerfile
  jenkins-slaves/jenkins-slave-argocd/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-argocd/README.md
Labels: approved, lgtm, size/M

#294 added jenkins helm slave
  .applier/group_vars/seed-hosts.yml
  jenkins-slaves/jenkins-slave-helm/Dockerfile
  jenkins-slaves/jenkins-slave-helm/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-helm/README.md
Labels: approved, lgtm, ok-to-test, size/M

#280 created a basic eap 7.2 Helm chart
  helm-charts/eap72/Chart.yaml
  helm-charts/eap72/README.md
  helm-charts/eap72/templates/NOTES.txt
  helm-charts/eap72/templates/buildconfig.yaml
  helm-charts/eap72/templates/deploymentconfig.yaml
  helm-charts/eap72/templates/imagestream.yaml
  helm-charts/eap72/templates/ping-service.yaml
  helm-charts/eap72/templates/route.yaml
  helm-charts/eap72/templates/secret.yaml
  helm-charts/eap72/templates/server-service.yaml
  helm-charts/eap72/templates/tests/pod.yaml
  helm-charts/eap72/values.yaml
Labels: approved, lgtm, size/L

#302 Update test scripts to output failed build logs
  TESTING.md
  _test/common.sh
  _test/setup.sh
Labels: approved, lgtm, size/M

#303 Only show Jenkins logs for JenkinsPipeline builds
  _test/setup.sh
Labels: approved, lgtm, size/XS
