Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-10, with the labels that each got.

#411 Fix wrongly named 'generic agent' file
  .openshift/templates/jenkins-agent-generic-template.yml
Labels: approved, lgtm, size/XS

#412 Update ansible version
  jenkins-agents/jenkins-agent-ansible/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#413 refactor dockerfile & update Jenkins base to 4.5
  jenkins-agents/jenkins-agent-ansible/Dockerfile
Labels: approved, lgtm, ok-to-test, size/M

#414 jenkins-agent-ansible add pip pkgs openshift and kubernetes
  jenkins-agents/jenkins-agent-ansible/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#407 Move to jenkins-agent-base:4.5
  .applier/group_vars/seed-hosts.yml
  jenkins-agents/jenkins-agent-arachni/Dockerfile
  jenkins-agents/jenkins-agent-erlang/Dockerfile
  jenkins-agents/jenkins-agent-golang/Dockerfile
  jenkins-agents/jenkins-agent-gradle/Dockerfile
  jenkins-agents/jenkins-agent-helm/Dockerfile
  jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
  jenkins-agents/jenkins-agent-mongodb/Dockerfile
  jenkins-agents/jenkins-agent-mvn/Dockerfile
  jenkins-agents/jenkins-agent-npm/Dockerfile
  jenkins-agents/jenkins-agent-python/Dockerfile
  jenkins-agents/jenkins-agent-ruby/Dockerfile
  jenkins-agents/jenkins-agent-rust/Dockerfile
Labels: approved, lgtm, size/S

#416 Adding vanity route + cert OCP template
  cert-manager-configs/.openshift/cert-manager.yml
  cert-manager-configs/.openshift/cert-utils-operator.yml
  cert-manager-configs/.openshift/ocpv4-certs.yml
  cert-manager-configs/.openshift/route-with-cert.yml
Labels: approved, lgtm, size/M
