Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-04, with the labels that each got.

#307 Various UX improvements and bug fixes to eap72 chart.
  helm-charts/eap72/README.md
  helm-charts/eap72/templates/NOTES.txt
  helm-charts/eap72/templates/buildconfig.yaml
  helm-charts/eap72/templates/deploymentconfig.yaml
  helm-charts/eap72/templates/route.yaml
  helm-charts/eap72/templates/secret.yaml
  helm-charts/eap72/templates/server-service.yaml
  helm-charts/eap72/templates/tests/pod.yaml
  helm-charts/eap72/values.yaml
Labels: approved, lgtm, ok-to-test, size/L

#309 Ubi8 asciidoctor
  ubi8-asciidoctor/.openshift/bc-ubi8-asciidoctor.yml
  ubi8-asciidoctor/Dockerfile
  ubi8-asciidoctor/README.md
Labels: approved, lgtm, ok-to-test, size/L

#308 ubi8-git and ubi8-google-api-python-client - init add
  ubi8-git/.openshift/bc-ubi8-git.yml
  ubi8-git/Dockerfile
  ubi8-git/README.md
  ubi8-google-api-python-client/.openshift/bc-ubi8-google-api-python-client.yml
  ubi8-google-api-python-client/Dockerfile
  ubi8-google-api-python-client/README.md
Labels: approved, lgtm, ok-to-test, size/L

#312 Add hostname and set Locale, fixes #311
  _test/rabbitmq.sh
  rabbitmq/.openshift/templates/imagestreams/images.yml
  rabbitmq/Dockerfile
Labels: approved, lgtm, size/M

#314 ubi8-git and ubi8-google-api - update to use registry.access.redhat.com/ubi8
  ubi8-git/Dockerfile
  ubi8-google-api-python-client/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#318 Enable jenkins git clone
  .applier/group_vars/seed-hosts.yml
  .openshift/templates/jenkins-pipeline-template-no-ocp-triggers.j2
Labels: approved, lgtm, size/M

#300 Add Jenkins Arachni agent to CI
  .applier/group_vars/seed-hosts.yml
  jenkins-slaves/jenkins-slave-arachni/Jenkinsfile.test
Labels: approved, lgtm, size/S

#317 ubi7-gitlab-runner - initial add
  gitlab-runners/ubi7-gitlab-runner/.openshift/bc-ubi7-gitlab-runner.yml
  gitlab-runners/ubi7-gitlab-runner/Dockerfile
  gitlab-runners/ubi7-gitlab-runner/README.md
  gitlab-runners/ubi7-gitlab-runner/entrypoint
  gitlab-runners/ubi8-asciidoctor/.openshift/bc-ubi8-asciidoctor.yml
  gitlab-runners/ubi8-asciidoctor/Dockerfile
  gitlab-runners/ubi8-asciidoctor/README.md
  gitlab-runners/ubi8-git/.openshift/bc-ubi8-git.yml
  gitlab-runners/ubi8-git/Dockerfile
  gitlab-runners/ubi8-git/README.md
  gitlab-runners/ubi8-google-api-python-client/.openshift/bc-ubi8-google-api-python-client.yml
  gitlab-runners/ubi8-google-api-python-client/Dockerfile
  gitlab-runners/ubi8-google-api-python-client/README.md
Labels: approved, lgtm, ok-to-test, size/L

#316 Added Helm 3 chart for motepair
  README.md
  motepair/.helmignore
  motepair/Chart.yaml
  motepair/README.md
  motepair/templates/NOTES.txt
  motepair/templates/_helpers.tpl
  motepair/templates/buildconfig.yaml
  motepair/templates/deploymentconfig.yaml
  motepair/templates/imagestream.yaml
  motepair/templates/route.yaml
  motepair/templates/service.yaml
  motepair/values.yaml
Labels: approved, lgtm, size/L

#320 Update rabbitmq configuration
  rabbitmq/.openshift/templates/builds/template.yml
  rabbitmq/.openshift/templates/configmaps/config.yml
  rabbitmq/.openshift/templates/deployments/template.yml
Labels: approved, lgtm, ok-to-test, size/M

#324 🐐 README changes to reflect Labs CI/CD being depricated 🐐
  README.md
Labels: approved, lgtm, size/XS

#325 🦆 FIX - Jenkins slave npm chrome dep 🦆
  jenkins-slaves/jenkins-slave-npm/Dockerfile
  jenkins-slaves/jenkins-slave-npm/README.md
Labels: approved, lgtm, size/XS

#326 🦅 ADD - yq for yaml manipulation as part of pipeline 🦅
  jenkins-slaves/jenkins-slave-argocd/Dockerfile
  jenkins-slaves/jenkins-slave-argocd/README.md
Labels: approved, lgtm, size/S

#323 Add support for pushing ubi8 git image to Quay
  .github/workflows/gitlab-runners-ubi8-git-pr.yaml
  .github/workflows/gitlab-runners-ubi8-git-publish.yaml
  README.md
  gitlab-runners/README.md
  gitlab-runners/ubi8-git/version.json
Labels: approved, lgtm, size/M

#327 Fix typo in GH Quay publish workflow
  .github/workflows/gitlab-runners-ubi8-git-publish.yaml
Labels: approved, bug, lgtm, size/XS

#328 Add CI tests for gradle, mongodb, npm & python jenkins agents
  .applier/group_vars/seed-hosts.yml
  jenkins-slaves/jenkins-slave-gradle/Dockerfile
  jenkins-slaves/jenkins-slave-gradle/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-gradle/ubi.repo
  jenkins-slaves/jenkins-slave-mongodb/Dockerfile
  jenkins-slaves/jenkins-slave-mongodb/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-npm/Jenkinsfile.test
  jenkins-slaves/jenkins-slave-python/Dockerfile
  jenkins-slaves/jenkins-slave-python/Jenkinsfile.test
Labels: approved, lgtm, size/L
