Repository redhat-cop/containers-quickstarts, pull requests merged in 2020-12, with the labels that each got.

#425 jenkins-agent-zap: Fix running in container + num_urls bug
  .applier/group_vars/seed-hosts.yml
  jenkins-agents/jenkins-agent-zap/Dockerfile
  jenkins-agents/jenkins-agent-zap/Jenkinsfile.test
  jenkins-agents/jenkins-agent-zap/policies/API-Minimal.policy
  jenkins-agents/jenkins-agent-zap/policies/Default Policy.policy
  jenkins-agents/jenkins-agent-zap/policies/St-High-Th-High.policy
  jenkins-agents/jenkins-agent-zap/policies/St-High-Th-Low.policy
  jenkins-agents/jenkins-agent-zap/policies/St-High-Th-Med.policy
  jenkins-agents/jenkins-agent-zap/policies/St-Ins-Th-High.policy
  jenkins-agents/jenkins-agent-zap/policies/St-Ins-Th-Low.policy
  jenkins-agents/jenkins-agent-zap/policies/St-Ins-Th-Med.policy
  jenkins-agents/jenkins-agent-zap/policies/St-Low-Th-High.policy
  jenkins-agents/jenkins-agent-zap/policies/St-Low-Th-Low.policy
  jenkins-agents/jenkins-agent-zap/policies/St-Low-Th-Med.policy
  jenkins-agents/jenkins-agent-zap/policies/St-Med-Th-High.policy
  jenkins-agents/jenkins-agent-zap/policies/St-Med-Th-Low.policy
  jenkins-agents/jenkins-agent-zap/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js
  jenkins-agents/jenkins-agent-zap/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
  jenkins-agents/jenkins-agent-zap/zap/zap-api-scan.py
  jenkins-agents/jenkins-agent-zap/zap/zap-baseline.py
  jenkins-agents/jenkins-agent-zap/zap/zap-full-scan.py
  jenkins-agents/jenkins-agent-zap/zap/zap-webswing.sh
  jenkins-agents/jenkins-agent-zap/zap/zap-x.sh
  jenkins-agents/jenkins-agent-zap/zap/zap_common.py
Labels: approved, lgtm, size/XXL

#423 jenkins-agent-golang: Use Go 1.15.6, update sonar-scanner version & update test + README
  jenkins-agents/jenkins-agent-golang/Dockerfile
  jenkins-agents/jenkins-agent-golang/Jenkinsfile.test
  jenkins-agents/jenkins-agent-golang/README.md
Labels: approved, lgtm, size/M

#424 Move to jenkins-agent-base:4.6
  .applier/group_vars/seed-hosts.yml
  jenkins-agents/jenkins-agent-ansible/Dockerfile
  jenkins-agents/jenkins-agent-ansible/contrib/bin/configure-slave
  jenkins-agents/jenkins-agent-ansible/contrib/bin/scl_enable
  jenkins-agents/jenkins-agent-ansible/scl_enable
  jenkins-agents/jenkins-agent-ansible/ubi.repo
  jenkins-agents/jenkins-agent-ansible/ubi8.repo
  jenkins-agents/jenkins-agent-arachni/Dockerfile
  jenkins-agents/jenkins-agent-erlang/Dockerfile
  jenkins-agents/jenkins-agent-graalvm/Dockerfile
  jenkins-agents/jenkins-agent-graalvm/ubi.repo
  jenkins-agents/jenkins-agent-graalvm/ubi8.repo
  jenkins-agents/jenkins-agent-gradle/Dockerfile
  jenkins-agents/jenkins-agent-gradle/ubi.repo
  jenkins-agents/jenkins-agent-helm/Dockerfile
  jenkins-agents/jenkins-agent-helm/scl_enable
  jenkins-agents/jenkins-agent-helm/ubi.repo
  jenkins-agents/jenkins-agent-helm/ubi8.repo
  jenkins-agents/jenkins-agent-mongodb/Dockerfile
  jenkins-agents/jenkins-agent-mongodb/mongodb-org-3.6.repo
  jenkins-agents/jenkins-agent-mongodb/ubi.repo
  jenkins-agents/jenkins-agent-mvn/Dockerfile
  jenkins-agents/jenkins-agent-npm/Dockerfile
  jenkins-agents/jenkins-agent-python/Dockerfile
  jenkins-agents/jenkins-agent-python/prepare-yum-repositories
  jenkins-agents/jenkins-agent-python/scl_enable
  jenkins-agents/jenkins-agent-python/ubi.repo
  jenkins-agents/jenkins-agent-python/ubi8.repo
  jenkins-agents/jenkins-agent-ruby/Dockerfile
  jenkins-agents/jenkins-agent-ruby/root/opt/app-root/etc/scl_enable
  jenkins-agents/jenkins-agent-ruby/ubi.repo
  jenkins-agents/jenkins-agent-ruby/ubi8.repo
  jenkins-agents/jenkins-agent-rust/Dockerfile
  jenkins-agents/jenkins-agent-rust/ubi.repo
  jenkins-agents/jenkins-agent-rust/ubi8.repo
Labels: approved, lgtm, size/XXL

#426 🦅 argocd 1.8.1 🦅
  jenkins-agents/jenkins-agent-argocd/Dockerfile
Labels: approved, lgtm, size/XS

#428 ignition file version updated
  ipa-server/.openshift/files/01-worker-sebool.yml
Labels: approved, lgtm, size/XS
