Repository redhat-cop/containers-quickstarts, pull requests merged in 2021-07, with the labels that each got.

#492 Add tower custom buildconfig
  _test/conftest.sh
  tower-ocp-custom/.applier/group_vars/seed-hosts.yml
  tower-ocp-custom/.applier/hosts
  tower-ocp-custom/.openshift/templates/tower-ocp-custom-image.yml
  tower-ocp-custom/README.md
  tower-ocp-custom/requirements.yml
Labels: approved, lgtm, size/L

#510 BUGFIX: Use openssl to verify Helm checksum
  tekton-task-images/helm/Dockerfile
Labels: approved, lgtm, size/XS

#511 Use redhat-actions/push-to-registry for github-runner image
  .github/workflows/github-runner-ubi8.yaml
Labels: approved, lgtm, size/S

#513 🌶️ argocd 2.0.5 🌶️
  jenkins-agents/jenkins-agent-argocd/Dockerfile
Labels: approved, lgtm, size/XS

#514 Modification of templates to be aligned with Cert-Manager v1.4.0
  cert-manager-configs/.openshift/cert-manager.yml
  cert-manager-configs/.openshift/ocpv4-certs.yml
  cert-manager-configs/.openshift/route-with-cert.yml
Labels: approved, lgtm, size/XS

#515 Update python-kopf-s2i for version 1.32.1
  build-s2i-python-kopf/Dockerfile
  build-s2i-python-kopf/build-template.yaml
  build-s2i-python-kopf/build/build_config.yaml
  build-s2i-python-kopf/examples/kopf-simple/build-template.yaml
  build-s2i-python-kopf/examples/kopf-simple/devfile.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/devfile.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/operator/operator.py
  build-s2i-python-kopf/install/requirements.txt
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/M
