Repository redhat-cop/containers-quickstarts, pull requests merged in 2021-03, with the labels that each got.

#445 Update ubi-bats utility version + buildah & podman actions
  .github/workflows/ubi8-bats-pr.yaml
  .github/workflows/ubi8-bats-publish.yaml
  utilities/ubi8-bats/Dockerfile
  utilities/ubi8-bats/buildah.sh
  utilities/ubi8-bats/test/unit.bats
  utilities/ubi8-bats/version.json
Labels: approved, lgtm, size/M

#447 Update Python Kopf s2i to 1.29.2
  .github/workflows/build-s2i-python-kopf-pr.yaml
  build-s2i-python-kopf/Dockerfile
  build-s2i-python-kopf/README.adoc
  build-s2i-python-kopf/build-template.yaml
  build-s2i-python-kopf/examples/kopf-simple/Dockerfile
  build-s2i-python-kopf/examples/kopf-simple/README.adoc
  build-s2i-python-kopf/examples/kopf-simple/build-template.yaml
  build-s2i-python-kopf/examples/kopf-simple/build/build_config.yaml
  build-s2i-python-kopf/examples/kopf-simple/build/custom/build_config.yaml
  build-s2i-python-kopf/examples/kopf-simple/build/custom/kustomization.yaml
  build-s2i-python-kopf/examples/kopf-simple/build/image_stream.yaml
  build-s2i-python-kopf/examples/kopf-simple/build/kustomization.yaml
  build-s2i-python-kopf/examples/kopf-simple/deploy-template.yaml
  build-s2i-python-kopf/examples/kopf-simple/deploy/deployment.yaml
  build-s2i-python-kopf/examples/kopf-simple/deploy/kustomization.yaml
  build-s2i-python-kopf/examples/kopf-simple/devfile.yaml
  build-s2i-python-kopf/examples/kopf-simple/kopf-opt.sh
  build-s2i-python-kopf/examples/kopf-simple/operator/operator.py
  build-s2i-python-kopf/examples/kopf-simple/rbac/kustomization.yaml
  build-s2i-python-kopf/examples/kopf-simple/rbac/role.yaml
  build-s2i-python-kopf/examples/kopf-simple/rbac/role_binding.yaml
  build-s2i-python-kopf/examples/kopf-simple/rbac/service_account.yaml
  build-s2i-python-kopf/examples/kopf-simple/requirements.txt
  build-s2i-python-kopf/examples/kopf-simple/test/configmap.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/README.adoc
  build-s2i-python-kopf/examples/openshift-template-deployer/devfile.yaml
  build-s2i-python-kopf/examples/openshift-template-deployer/operator/operator.py
  build-s2i-python-kopf/imagestream.yaml
  build-s2i-python-kopf/install/python3-install.sh
  build-s2i-python-kopf/install/requirements.txt
  build-s2i-python-kopf/peering-crds.yaml
  build-s2i-python-kopf/s2i/run
  build-s2i-python-kopf/template.yaml
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/L

#448 asciidoctor-pdf image: Move home out of a mounted volume
  utilities/ubi8-asciidoctor/Dockerfile
  utilities/ubi8-asciidoctor/version.json
Labels: approved, lgtm, ok-to-test, size/XS

#444 Change RabbitMQ to use ubi-minimal:8
  rabbitmq/.openshift/templates/builds/template.yml
  rabbitmq/.openshift/templates/imagestreams/images.yml
  rabbitmq/Dockerfile
Labels: approved, lgtm, size/S

#449 Add explicit all namespaces flag fo kopf s2i run
  build-s2i-python-kopf/s2i/run
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/XS

#451 build-s2i-python-kopf fix peering and example improvements
  build-s2i-python-kopf/examples/kopf-simple/README.adoc
  build-s2i-python-kopf/examples/kopf-simple/operator/operator.py
  build-s2i-python-kopf/s2i/run
Labels: approved, lgtm, size/M

#453 Bump build-s2i-python-kopf to v1.29.2
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/XS

#454 RabbitMQ migration to Bats & Helm for testing
  rabbitmq/chart/templates/deployment.yaml
  rabbitmq/test/acceptance/_helpers.bash
  rabbitmq/test/acceptance/rabbitmq.bats
Labels: approved, lgtm, size/M

#457 FIX: Jenkins Zap Agent pip url update
  jenkins-agents/jenkins-agent-zap/Dockerfile
Labels: approved, lgtm, size/XS

#446 Update RabbitMQ to 3.1.13 & Erlang to 23.2.5
  rabbitmq/Dockerfile
  rabbitmq/chart/Chart.yaml
  rabbitmq/version.json
Labels: approved, lgtm, size/S

#455 RabbitMQ HA (anti affinity) fix
  rabbitmq/chart/templates/_helpers.tpl
  rabbitmq/chart/templates/deployment.yaml
  rabbitmq/chart/values.yaml
  rabbitmq/test/unit/statefulset.bats
Labels: approved, bug, lgtm, size/M

#459 Sonarqube: update to 7.9.6 + support updating plugins
  sonarqube/.applier/group_vars/seed-hosts.yml
  sonarqube/Dockerfile
  sonarqube/plugins.sh
Labels: approved, lgtm, size/M

#450 Enable prometheus scraping endpoint
  _test/rabbitmq.sh
  rabbitmq/.openshift/templates/configmaps/config.yml
  rabbitmq/.openshift/templates/deployments/template.yml
  rabbitmq/chart/templates/configmap.yaml
  rabbitmq/chart/templates/deployment.yaml
  rabbitmq/chart/values.yaml
  rabbitmq/test/acceptance/rabbitmq.bats
  rabbitmq/test/unit/service.bats
Labels: approved, lgtm, size/M

#458 Tekton Task images 🏄‍♀️
  .github/workflows/tekton-task-images-conftest-pr.yaml
  .github/workflows/tekton-task-images-conftest-publish.yaml
  .github/workflows/tekton-task-images-helm-pr.yaml
  .github/workflows/tekton-task-images-helm-publish.yaml
  tekton-task-images/conftest/Dockerfile
  tekton-task-images/conftest/README.md
  tekton-task-images/conftest/VERSION
  tekton-task-images/helm/Dockerfile
  tekton-task-images/helm/README.md
  tekton-task-images/helm/VERSION
Labels: approved, lgtm, size/L

#460 🦀 fix static linking issue native mode 🦀
  jenkins-agents/jenkins-agent-graalvm/Dockerfile
Labels: approved, lgtm, size/XS

#462 Replace of retired LE X3 CA certficate with LE R3
  cert-manager-configs/.openshift/ocpv4-certs.yml
Labels: approved, lgtm, ok-to-test, size/M

#463 Update GH actions to use redhat-actions for build & publish
  .github/workflows/build-s2i-python-kopf-pr.yaml
  .github/workflows/build-s2i-python-kopf-publish.yaml
  .github/workflows/conftest.yaml
  .github/workflows/github-runner-ubi8.yaml
  .github/workflows/jenkins-agent-image-mgmt-pr.yaml
  .github/workflows/jenkins-agent-image-mgmt-publish.yaml
  .github/workflows/jenkins-agent-python-pr.yaml
  .github/workflows/jenkins-agent-python-publish.yaml
  .github/workflows/rabbitmq-pr.yaml
  .github/workflows/rabbitmq-publish.yaml
  .github/workflows/tekton-task-images-conftest-pr.yaml
  .github/workflows/tekton-task-images-conftest-publish.yaml
  .github/workflows/tekton-task-images-helm-pr.yaml
  .github/workflows/tekton-task-images-helm-publish.yaml
  .github/workflows/ubi7-gitlab-runner-pr.yaml
  .github/workflows/ubi7-gitlab-runner-publish.yaml
  .github/workflows/ubi8-asciidoctor-pr.yaml
  .github/workflows/ubi8-asciidoctor-publish.yaml
  .github/workflows/ubi8-git-pr.yaml
  .github/workflows/ubi8-git-publish.yaml
  .github/workflows/ubi8-google-api-python-client-pr.yaml
  .github/workflows/ubi8-google-api-python-client-publish.yaml
Labels: approved, lgtm, size/L

#464 bumped versions and fixed source repo for build-docker-generic
  build-docker-generic/.applier/group_vars/seed-hosts.yml
  build-docker-generic/Dockerfile
  build-docker-generic/requirements.yml
Labels: approved, lgtm, size/S

#466 bumped versions and fixed docs for jekyll
  build-s2i-jekyll/.applier/group_vars/seed-hosts.yml
  build-s2i-jekyll/README.md
  build-s2i-jekyll/requirements.yml
Labels: approved, lgtm, size/XS

#465 bumped versions and fixed docs for gows
  build-s2i-gows/.applier/group_vars/seed-hosts.yml
  build-s2i-gows/README.md
  build-s2i-gows/requirements.yml
Labels: approved, lgtm, size/XS

#467 bumped versions and fixed docs for liberty
  build-s2i-liberty/.applier/group_vars/seed-hosts.yml
  build-s2i-liberty/README.md
  build-s2i-liberty/requirements.yml
Labels: approved, lgtm, size/XS

#469 bumped versions for build-s2i-executable
  build-s2i-executable/.applier/group_vars/seed-hosts.yml
  build-s2i-executable/requirements.yml
Labels: approved, lgtm, size/XS

#473 Syntax fixes for GH Actions
  .github/workflows/build-s2i-python-kopf-pr.yaml
  .github/workflows/build-s2i-python-kopf-publish.yaml
  .github/workflows/github-runner-ubi8.yaml
  .github/workflows/jenkins-agent-image-mgmt-publish.yaml
  .github/workflows/jenkins-agent-python-pr.yaml
  .github/workflows/jenkins-agent-python-publish.yaml
  .github/workflows/rabbitmq-pr.yaml
  .github/workflows/rabbitmq-publish.yaml
  .github/workflows/tekton-task-images-conftest-pr.yaml
  .github/workflows/tekton-task-images-conftest-publish.yaml
  .github/workflows/tekton-task-images-helm-pr.yaml
  .github/workflows/tekton-task-images-helm-publish.yaml
  .github/workflows/ubi7-gitlab-runner-pr.yaml
  .github/workflows/ubi7-gitlab-runner-publish.yaml
  .github/workflows/ubi8-asciidoctor-pr.yaml
  .github/workflows/ubi8-asciidoctor-publish.yaml
  .github/workflows/ubi8-bats-pr.yaml
  .github/workflows/ubi8-bats-publish.yaml
  .github/workflows/ubi8-git-pr.yaml
  .github/workflows/ubi8-git-publish.yaml
  .github/workflows/ubi8-google-api-python-client-pr.yaml
  .github/workflows/ubi8-google-api-python-client-publish.yaml
Labels: approved, lgtm, size/M
