Repository redhat-cop/containers-quickstarts, pull requests merged in 2021-04, with the labels that each got.

#475 moved motepair to deprecated
  README.md
  _test/conftest.sh
  deprecated/README.md
  deprecated/motepair/.helmignore
  deprecated/motepair/Chart.yaml
  deprecated/motepair/README.md
  deprecated/motepair/templates/NOTES.txt
  deprecated/motepair/templates/_helpers.tpl
  deprecated/motepair/templates/buildconfig.yaml
  deprecated/motepair/templates/deploymentconfig.yaml
  deprecated/motepair/templates/imagestream.yaml
  deprecated/motepair/templates/route.yaml
  deprecated/motepair/templates/service.yaml
  deprecated/motepair/values.yaml
Labels: approved, lgtm, size/S

#476 moved build-s2i-play to deprecated
  README.md
  _test/conftest.sh
  deprecated/build-s2i-play/.applier/group_vars/seed-hosts.yml
  deprecated/build-s2i-play/.applier/hosts
  deprecated/build-s2i-play/.gitignore
  deprecated/build-s2i-play/.openshift/params/build
  deprecated/build-s2i-play/.openshift/params/deployment
  deprecated/build-s2i-play/.openshift/templates/build.yml
  deprecated/build-s2i-play/.openshift/templates/deployment.yml
  deprecated/build-s2i-play/Dockerfile
  deprecated/build-s2i-play/README.md
  deprecated/build-s2i-play/images/play-logo.png
  deprecated/build-s2i-play/requirements.yml
  deprecated/build-s2i-play/s2i/assemble
  deprecated/build-s2i-play/s2i/run
Labels: approved, lgtm, size/S

#477 removed nexus as duplicated in helm-repo
  _test/conftest.sh
  nexus/README.md
  nexus/chart/nexus/.gitignore
  nexus/chart/nexus/.helmignore
  nexus/chart/nexus/Chart.yaml
  nexus/chart/nexus/README.md
  nexus/chart/nexus/templates/NOTES.txt
  nexus/chart/nexus/templates/_helpers.tpl
  nexus/chart/nexus/templates/rolebinding.yaml
  nexus/chart/nexus/values.yaml
Labels: approved, lgtm, size/L

#478 removed eap chart
  _test/conftest.sh
  eap/README.md
  eap/chart/Chart.yaml
  eap/chart/README.md
  eap/chart/templates/NOTES.txt
  eap/chart/templates/buildconfig.yaml
  eap/chart/templates/deploymentconfig.yaml
  eap/chart/templates/imagestream.yaml
  eap/chart/templates/ping-service.yaml
  eap/chart/templates/route.yaml
  eap/chart/templates/secret.yaml
  eap/chart/templates/server-service.yaml
  eap/chart/templates/tests/pod.yaml
  eap/chart/values.yaml
Labels: approved, lgtm, size/L

#480 🐧 ADD conftest to helm agent and UPDATE versions 🐧
  jenkins-agents/jenkins-agent-conftest/README.md
  jenkins-agents/jenkins-agent-helm/Dockerfile
  jenkins-agents/jenkins-agent-helm/Jenkinsfile.test
Labels: approved, lgtm, size/S

#479 fixed build/publish ci failing
  .github/workflows/build-s2i-python-kopf-pr.yaml
  .github/workflows/build-s2i-python-kopf-publish.yaml
  .github/workflows/github-runner-ubi8.yaml
  .github/workflows/jenkins-agent-image-mgmt-pr.yaml
  .github/workflows/jenkins-agent-image-mgmt-publish.yaml
  .github/workflows/jenkins-agent-python-pr.yaml
  .github/workflows/jenkins-agent-python-publish.yaml
  .github/workflows/rabbitmq-pr.yaml
  .github/workflows/rabbitmq-publish.yaml
  .github/workflows/tekton-task-images-conftest-pr.yaml
  .github/workflows/tekton-task-images-conftest-publish.yaml
  .github/workflows/tekton-task-images-helm-pr.yaml
  .github/workflows/tekton-task-images-helm-publish.yaml
  .github/workflows/ubi7-gitlab-runner-pr.yaml
  .github/workflows/ubi7-gitlab-runner-publish.yaml
  .github/workflows/ubi8-asciidoctor-pr.yaml
  .github/workflows/ubi8-asciidoctor-publish.yaml
  .github/workflows/ubi8-bats-pr.yaml
  .github/workflows/ubi8-bats-publish.yaml
  .github/workflows/ubi8-git-pr.yaml
  .github/workflows/ubi8-git-publish.yaml
  .github/workflows/ubi8-google-api-python-client-pr.yaml
  .github/workflows/ubi8-google-api-python-client-publish.yaml
Labels: approved, lgtm, size/L

#481 GH buildah-build action needs space separated tags
  .github/workflows/build-s2i-python-kopf-publish.yaml
  .github/workflows/jenkins-agent-image-mgmt-publish.yaml
  .github/workflows/jenkins-agent-python-publish.yaml
  .github/workflows/rabbitmq-publish.yaml
  .github/workflows/tekton-task-images-conftest-publish.yaml
  .github/workflows/tekton-task-images-helm-publish.yaml
  .github/workflows/ubi7-gitlab-runner-publish.yaml
  .github/workflows/ubi8-asciidoctor-publish.yaml
  .github/workflows/ubi8-git-publish.yaml
  .github/workflows/ubi8-google-api-python-client-publish.yaml
Labels: approved, lgtm, size/S

#483 Downgraded to ubuntu-18.04 for jenkins image mgt publish
  .github/workflows/jenkins-agent-image-mgmt-publish.yaml
Labels: approved, lgtm, size/XS

#488 Use more descriptive names for Tekton Task images
  .github/workflows/tekton-task-images-conftest-publish.yaml
  .github/workflows/tekton-task-images-helm-publish.yaml
Labels: approved, lgtm, size/XS

#489 Update Tekton Task image packages to resolve openssl RHSA-2021:1024
  tekton-task-images/conftest/Dockerfile
  tekton-task-images/helm/Dockerfile
Labels: approved, lgtm, size/XS

#493 Add dependabot for github actions
  .github/dependabot.yaml
Labels: approved, lgtm, size/XS
