Repository redhat-cop/containers-quickstarts, pull requests merged in 2021-08, with the labels that each got.

#516 🦩 jenkins-agent-graalvm - updates for latest version 🦩
  jenkins-agents/jenkins-agent-graalvm/Dockerfile
Labels: approved, lgtm, size/S

#517 🦆 ADD - yq to tekkers task and version bump 🦆
  tekton-task-images/helm/Dockerfile
  tekton-task-images/helm/VERSION
Labels: approved, lgtm, size/S

#518 Fixing up README for IPA/IdM deployment
  ipa-server/README.md
Labels: approved, lgtm, size/S

#519 🐉 ADD - wider group of people to help maintain repo 🐉
  OWNERS
Labels: approved, lgtm, size/XS

#520 Bump python Kopf S2i builder to v1.33.0
  build-s2i-python-kopf/install/requirements.txt
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/XS

#522 🐩 cosign Jenkins agent added 🐩
  jenkins-agents/jenkins-agent-cosign/Dockerfile
  jenkins-agents/jenkins-agent-cosign/Jenkinsfile.test
  jenkins-agents/jenkins-agent-cosign/README.md
Labels: size/M, approved, lgtm
