Repository redhat-cop/containers-quickstarts, pull requests merged in 2021-09, with the labels that each got.

#523 FIX: RabbitMQ keyserver update to pass builds + version updates
  rabbitmq/Dockerfile
  rabbitmq/version.json
Labels: size/S, approved, lgtm

#524 🐓 ADD - kube-linter to the jenkins image for helm 🐓
  jenkins-agents/jenkins-agent-helm/Dockerfile
  jenkins-agents/jenkins-agent-helm/Jenkinsfile.test
Labels: size/S, approved, lgtm

#525 Update Jenkins Agent base images to 4.8 + minor improvements
  jenkins-agents/jenkins-agent-ansible/Dockerfile
  jenkins-agents/jenkins-agent-arachni/Dockerfile
  jenkins-agents/jenkins-agent-argocd/Dockerfile
  jenkins-agents/jenkins-agent-conftest/Dockerfile
  jenkins-agents/jenkins-agent-cosign/Dockerfile
  jenkins-agents/jenkins-agent-erlang/Dockerfile
  jenkins-agents/jenkins-agent-golang/Dockerfile
  jenkins-agents/jenkins-agent-graalvm/Dockerfile
  jenkins-agents/jenkins-agent-gradle/Dockerfile
  jenkins-agents/jenkins-agent-helm/Dockerfile
  jenkins-agents/jenkins-agent-helm/Jenkinsfile.test
  jenkins-agents/jenkins-agent-hugo/Dockerfile
  jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
  jenkins-agents/jenkins-agent-mongodb/Dockerfile
  jenkins-agents/jenkins-agent-mvn/Dockerfile
  jenkins-agents/jenkins-agent-npm/Dockerfile
  jenkins-agents/jenkins-agent-python/Dockerfile
  jenkins-agents/jenkins-agent-ruby/Dockerfile
  jenkins-agents/jenkins-agent-rust/Dockerfile
Labels: approved, lgtm, size/L

#526 FIX: Add python3-devel to fix ubi8-asciidoctor build
  utilities/ubi8-asciidoctor/Dockerfile
  utilities/ubi8-asciidoctor/version.json
Labels: approved, lgtm, size/XS

#527 Bump kopf version to 1.34.0
  build-s2i-python-kopf/install/requirements.txt
  build-s2i-python-kopf/version.json
Labels: approved, lgtm, size/XS
