Repository redhat-cop/containers-quickstarts, pull requests merged in 2021-11, with the labels that each got.

#534 Refresh versions of toolbox image and add zip because I need it
  tool-box/Dockerfile
  tool-box/README.md
Labels: size/S, approved, lgtm

#535 Upgrade pipe to fix build issue
  tool-box/Dockerfile
Labels: approved, lgtm, size/XS

#536 Fix broken permissions in Jenkins agents using Python
  jenkins-agents/jenkins-agent-ansible/Dockerfile
  jenkins-agents/jenkins-agent-ansible/Jenkinsfile.test
  jenkins-agents/jenkins-agent-graalvm/Jenkinsfile.test
  jenkins-agents/jenkins-agent-helm/Dockerfile
  jenkins-agents/jenkins-agent-helm/Jenkinsfile.test
  jenkins-agents/jenkins-agent-python/Dockerfile
  jenkins-agents/jenkins-agent-python/Jenkinsfile.test
  jenkins-agents/jenkins-agent-python/version.json
Labels: size/S, approved, lgtm

#538 Update Jenkins Agent base images to 4.9 + add cosign & image-mgmt tests
  .applier/group_vars/seed-hosts.yml
  jenkins-agents/jenkins-agent-ansible/Dockerfile
  jenkins-agents/jenkins-agent-arachni/Dockerfile
  jenkins-agents/jenkins-agent-argocd/Dockerfile
  jenkins-agents/jenkins-agent-cosign/Dockerfile
  jenkins-agents/jenkins-agent-erlang/Dockerfile
  jenkins-agents/jenkins-agent-golang/Dockerfile
  jenkins-agents/jenkins-agent-graalvm/Dockerfile
  jenkins-agents/jenkins-agent-gradle/Dockerfile
  jenkins-agents/jenkins-agent-helm/Dockerfile
  jenkins-agents/jenkins-agent-hugo/Dockerfile
  jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
  jenkins-agents/jenkins-agent-mongodb/Dockerfile
  jenkins-agents/jenkins-agent-mvn/Dockerfile
  jenkins-agents/jenkins-agent-npm/Dockerfile
  jenkins-agents/jenkins-agent-python/Dockerfile
  jenkins-agents/jenkins-agent-ruby/Dockerfile
  jenkins-agents/jenkins-agent-rust/Dockerfile
Labels: size/M, approved, lgtm

#537 Fix a few README URLs
  jenkins-agents/jenkins-agent-ruby/README.md
  rabbitmq/README.md
Labels: approved, lgtm, size/XS

#532 Update skopeo to 1.5.0 in jenkins-agent-image-mgmt
  jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
  jenkins-agents/jenkins-agent-image-mgmt/README.md
  jenkins-agents/jenkins-agent-image-mgmt/version.json
Labels: size/S, approved, lgtm

#539 Update python kopf s2i to 1.35.3
  build-s2i-python-kopf/imagestream.yaml
  build-s2i-python-kopf/install/requirements.txt
  build-s2i-python-kopf/version.json
Labels: size/M, approved, lgtm
