Repository redhat-cop/containers-quickstarts, pull requests merged in 2021-05, with the labels that each got.

#499 Deleted .travis.yml
  .travis.yml
Labels: approved, lgtm, size/M

#501 🐻 ADD - hugo static site builder 🐻
  jenkins-agents/jenkins-agent-hugo/Dockerfile
  jenkins-agents/jenkins-agent-hugo/Jenkinsfile.test
  jenkins-agents/jenkins-agent-hugo/README.md
Labels: approved, lgtm, size/M

#502 🐭 ADD - Hugo Extended binary for scss compilation 🐭
  jenkins-agents/jenkins-agent-hugo/Dockerfile
Labels: approved, lgtm, size/XS

#504 Add jenkins-agent-hugo to CI test
  .applier/group_vars/seed-hosts.yml
Labels: approved, lgtm, size/XS

#505 Update jenkins-agent-base to 4.7
  .applier/group_vars/seed-hosts.yml
  jenkins-agents/jenkins-agent-ansible/Dockerfile
  jenkins-agents/jenkins-agent-arachni/Dockerfile
  jenkins-agents/jenkins-agent-argocd/Dockerfile
  jenkins-agents/jenkins-agent-erlang/Dockerfile
  jenkins-agents/jenkins-agent-golang/Dockerfile
  jenkins-agents/jenkins-agent-graalvm/Dockerfile
  jenkins-agents/jenkins-agent-gradle/Dockerfile
  jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
  jenkins-agents/jenkins-agent-mongodb/Dockerfile
  jenkins-agents/jenkins-agent-mvn/Dockerfile
  jenkins-agents/jenkins-agent-npm/Dockerfile
  jenkins-agents/jenkins-agent-python/Dockerfile
  jenkins-agents/jenkins-agent-ruby/Dockerfile
  jenkins-agents/jenkins-agent-rust/Dockerfile
Labels: approved, lgtm, size/M

#500 Update to latest upstream Asciidoctor versions
  utilities/ubi8-asciidoctor/Dockerfile
  utilities/ubi8-asciidoctor/version.json
Labels: approved, lgtm, ok-to-test, size/M
