Repository redhat-cop/containers-quickstarts, pull requests merged in 2022-03, with the labels that each got.

#571 FIX: Avoid Docker Hub rate limit for Zap Agent
  .applier/group_vars/seed-hosts.yml
  jenkins-agents/jenkins-agent-zap/Dockerfile
Labels: approved, lgtm, size/XS

#572 ubi8-asciidcotor - add asciidcotor-reducer gem
  utilities/ubi8-asciidoctor/Dockerfile
Labels: size/XS

#563 added build ci for jenkins agents
  .github/workflows/jenkins-agent-ansible-pr.yaml
  .github/workflows/jenkins-agent-arachni-pr.yaml
  .github/workflows/jenkins-agent-argocd-pr.yaml
  .github/workflows/jenkins-agent-conftest-pr.yaml
  .github/workflows/jenkins-agent-cosign-pr.yaml
  .github/workflows/jenkins-agent-erlang-pr.yaml
  .github/workflows/jenkins-agent-golang-pr.yaml
  .github/workflows/jenkins-agent-graalvm-pr.yaml
  .github/workflows/jenkins-agent-gradle-pr.yaml
  .github/workflows/jenkins-agent-helm-pr.yaml
  .github/workflows/jenkins-agent-hugo-pr.yaml
  .github/workflows/jenkins-agent-mongodb-pr.yaml
  .github/workflows/jenkins-agent-mvn-pr.yaml
  .github/workflows/jenkins-agent-npm-pr.yaml
  .github/workflows/jenkins-agent-ruby-pr.yaml
  .github/workflows/jenkins-agent-rust-pr.yaml
  .github/workflows/jenkins-agent-zap-pr.yaml
Labels: size/L
