Repository redhat-cop/containers-quickstarts, pull requests merged in 2022-02, with the labels that each got.

#549 Add helm binary to Tower image
  tower-ocp-custom/.openshift/templates/tower-ocp-custom-image.yml
Labels: approved, lgtm, size/XS

#550 [Tower Custom Image] Revert addition of helm binary
  tower-ocp-custom/.openshift/templates/tower-ocp-custom-image.yml
Labels: approved, lgtm, size/XS

#551 Fix jenkins-agent-ruby rubygem issue
  jenkins-agents/jenkins-agent-ruby/Dockerfile
Labels: approved, lgtm, size/XS

#554 updated to ubuntu-latest
  .github/workflows/build-s2i-python-kopf-pr.yaml
  .github/workflows/build-s2i-python-kopf-publish.yaml
  .github/workflows/conftest.yaml
  .github/workflows/github-runner-ubi8.yaml
  .github/workflows/jenkins-agent-image-mgmt-pr.yaml
  .github/workflows/jenkins-agent-image-mgmt-publish.yaml
  .github/workflows/jenkins-agent-python-pr.yaml
  .github/workflows/jenkins-agent-python-publish.yaml
  .github/workflows/rabbitmq-pr.yaml
  .github/workflows/rabbitmq-publish.yaml
  .github/workflows/tekton-task-images-conftest-pr.yaml
  .github/workflows/tekton-task-images-conftest-publish.yaml
  .github/workflows/tekton-task-images-helm-pr.yaml
  .github/workflows/tekton-task-images-helm-publish.yaml
  .github/workflows/ubi7-gitlab-runner-pr.yaml
  .github/workflows/ubi7-gitlab-runner-publish.yaml
  .github/workflows/ubi8-bats-pr.yaml
  .github/workflows/ubi8-bats-publish.yaml
  .github/workflows/ubi8-git-pr.yaml
  .github/workflows/ubi8-git-publish.yaml
  .github/workflows/ubi8-google-api-python-client-pr.yaml
  .github/workflows/ubi8-google-api-python-client-publish.yaml
Labels: size/M, approved, lgtm

#556 upgraded to ruby 2.7 for ascidoctor
  .github/workflows/ubi8-asciidoctor-pr.yaml
  .github/workflows/ubi8-asciidoctor-publish.yaml
  utilities/ubi8-asciidoctor/Dockerfile
  utilities/ubi8-asciidoctor/version.json
Labels: size/S, approved, lgtm

#552 Switch to Ruby 2.7 in jenkins-agent-ruby image
  jenkins-agents/jenkins-agent-ruby/Dockerfile
Labels: approved, lgtm, size/XS

#565 updated base and mvn cdn url to fix build
  s2i-mvn-gradle/Dockerfile
Labels: approved, lgtm, size/XS

#564 updated base image to fix yum failure on build
  hygieia/Dockerfile
Labels: approved, lgtm, size/XS

#566 fixed curl missing
  sonarqube/Dockerfile
Labels: approved, lgtm, size/XS

#558 split gitlab runner into 2 files
  .github/workflows/github-runner-ubi8-pr.yaml
  .github/workflows/github-runner-ubi8-publish.yaml
Labels: size/M, approved, lgtm

#557 added ghcr to publish ci and remove branch filtering to always publish on push
  .github/workflows/build-s2i-python-kopf-publish.yaml
  .github/workflows/jenkins-agent-image-mgmt-publish.yaml
  .github/workflows/jenkins-agent-python-publish.yaml
  .github/workflows/rabbitmq-publish.yaml
  .github/workflows/tekton-task-images-conftest-publish.yaml
  .github/workflows/tekton-task-images-helm-publish.yaml
  .github/workflows/ubi7-gitlab-runner-publish.yaml
  .github/workflows/ubi8-asciidoctor-publish.yaml
  .github/workflows/ubi8-bats-publish.yaml
  .github/workflows/ubi8-git-publish.yaml
  .github/workflows/ubi8-google-api-python-client-publish.yaml
Labels: approved, lgtm, size/L

#567 replaced version code with central version action
  .github/workflows/build-s2i-python-kopf-pr.yaml
  .github/workflows/build-s2i-python-kopf-publish.yaml
  .github/workflows/jenkins-agent-image-mgmt-pr.yaml
  .github/workflows/jenkins-agent-image-mgmt-publish.yaml
  .github/workflows/jenkins-agent-python-pr.yaml
  .github/workflows/jenkins-agent-python-publish.yaml
  .github/workflows/rabbitmq-pr.yaml
  .github/workflows/rabbitmq-publish.yaml
  .github/workflows/tekton-task-images-conftest-pr.yaml
  .github/workflows/tekton-task-images-conftest-publish.yaml
  .github/workflows/tekton-task-images-helm-pr.yaml
  .github/workflows/tekton-task-images-helm-publish.yaml
  .github/workflows/ubi7-gitlab-runner-pr.yaml
  .github/workflows/ubi7-gitlab-runner-publish.yaml
  .github/workflows/ubi8-asciidoctor-pr.yaml
  .github/workflows/ubi8-asciidoctor-publish.yaml
  .github/workflows/ubi8-bats-pr.yaml
  .github/workflows/ubi8-bats-publish.yaml
  .github/workflows/ubi8-git-pr.yaml
  .github/workflows/ubi8-git-publish.yaml
  .github/workflows/ubi8-google-api-python-client-pr.yaml
  .github/workflows/ubi8-google-api-python-client-publish.yaml
  jenkins-agents/jenkins-agent-python/version.json
  ubi7-gitlab-runner/version.json
  utilities/ubi8-asciidoctor/version.json
  utilities/ubi8-git/version.json
  utilities/ubi8-google-api-python-client/version.json
Labels: approved, lgtm, size/L

#569 added annotation to call out that jenkinsPipelineStrategy deprecated
  .openshift/templates/jenkins-pipeline-template-no-ocp-triggers.j2
Labels: approved, lgtm, size/XS
